name: ci

on:
  push:
    branches:  [ main, develop, fixlid ]
    tags:
      - 'v*.*.*'

  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn format
      - run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get architecture from platform
        id: arch
        run: echo "arch=$(echo ${{ matrix.platform }} | cut -d '/' -f 2)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            # Gera uma tag específica para a arquitetura, ex: 'main-amd64'
            ${{ github.ref_name }}-${{ steps.arch.outputs.arch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by platform
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  merge-manifests:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for final tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            # Gera a tag final sem o sufixo da arquitetura, ex: 'main'
            ${{ github.ref_name }}

      - name: Create and push manifest
        run: |
          docker manifest create ${{ steps.meta.outputs.tags }} \
            --amend ghcr.io/${{ github.repository }}:${{ github.ref_name }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ github.ref_name }}-arm64
          docker manifest push ${{ steps.meta.outputs.tags }}